/*
 * Intent Policy API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: genix.li@leyantech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jayqqaa12.jbase.spring.mvc.resp.page;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * Pages
 */

@Data
@Accessors(chain = true)
public class Pages {

  @JsonProperty("pageNum")
  private Integer pageNum = null;

  @JsonProperty("pageSize")
  private Integer pageSize = null;

  @JsonProperty("totalPages")
  private Integer totalPages = null;

  @JsonProperty("totalRows")
  private Integer totalRows = null;



  public Pages pageNum(Integer pageNum) {
    this.pageNum = pageNum;
    return this;
  }



  public Pages pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }



  public Pages totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }



  public Pages totalRows(Integer totalRows) {
    this.totalRows = totalRows;
    return this;
  }




}
